services:
  app:
    build: .
    container_name: vue_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
volumes:
  node_modules: